In [170]:
#have to import numpy and pandas in each notebook
import numpy as np
import pandas as pd

## **Task 1: NumPy Basics**

### **NumPy Array Creation**
* Create a 1D NumPy array of integers from 1 to 20.
* Create a 2D NumPy array (5x4) filled with random numbers.
* Display both arrays.

In [173]:
#creates 1D array, () insures numbers 1 to 20 that are integers
arr = np.arange(1,21)
#creates 2D array and randomizes numbers, 5,4 sets the shape
arr2 = np.random.rand(5, 4)
print(arr)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[0.88159286 0.91585092 0.39663945 0.02557356]
 [0.37315316 0.89849639 0.72388638 0.8116102 ]
 [0.59187148 0.01331889 0.06810183 0.32637616]
 [0.74913234 0.11932994 0.14624147 0.27636312]
 [0.95951447 0.96866566 0.65227639 0.16493104]]

### **Array Indexing and Slicing**
* Extract all even numbers from the 1D array.
* Extract the second and fourth row from the 2D array

In [175]:
even_numbers = arr[arr % 2 == 0]
#sets an array with just even numbers then prints
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]

In [176]:
#extracts rows 1 and 3 out of the 5 and prints the whole row all columns
print(arr2[1, :]) 
print(arr2[3, :])

[0.37315316 0.89849639 0.72388638 0.8116102 ]
[0.74913234 0.11932994 0.14624147 0.27636312]

### **Mathematical Operations**
* Create a NumPy array of numbers from 10 to 100 with a step of 10.
* Perform element-wise square and square root operations on this array

In [178]:
#array from 10 to 100 with steps of 10
a = np.arange(10, 101,10)
#makes element-wise square and sqaure root form given array
squared_a = np.square(a)
sqrt_a = np.sqrt(a) 
print("Square:", squared_a)
print("Square Roots:", sqrt_a)

Square: [  100   400   900  1600  2500  3600  4900  6400  8100 10000]
Square Roots: [ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781  7.74596669
  8.36660027  8.94427191  9.48683298 10.        ]

### **Statistical Operations**
* Generate a 3x3 NumPy array of random integers between 1 and 50.
* Compute the mean, median, and standard deviation.

In [180]:
#3 by 3 array with integers from 1 to 50
b = np.random.randint (1,50,(3, 3))
print(b)
#gives the descriptive statistics
print('Mean:', np.mean(b))
print('Median:', np.median(b))
print('Standard Deviation:', np.std(b))

[[29 11 48]
 [44  7 37]
 [ 7  5 44]]
Mean: 25.77777777777778
Median: 29.0
Standard Deviation: 17.1579445659553

## **Task 2: Pandas Basics**

### **Data Loading and Overview**
* Load the dataset using Pandas.
* Display the first five rows.
* Show dataset information and check for missing values.
* Copy the original data to another data frame, df_new before doing any activities below
(sec 2.2 onwards).

In [183]:
#calling the file from notebook and printing
df = pd.read_csv("project1_part2_data.csv")
#head prints first 5 rows
print(df.head())
#shows dataset info
print(df.info()) 
#checks for missing values
print(df.isnull().sum())
#copy dstaset
df_new = df.copy()

   ID           Name   Age   Salary  Department    Position  \
0   1  Alice Johnson  49.0  46910.0  Operations  Consultant
1   2  Michael Smith  28.0  40206.0          IT     Manager
2   3  Emma Williams  30.0  63419.0       Sales     Analyst
3   4    David Brown  29.0  90636.0          HR   Executive
4   5   Olivia Jones  33.0      NaN   Marketing  Consultant

   Work Experience (Years) Education Level
0                       13             PhD
1                        9       Associate
2                       15             PhD
3                       13      Bachelor's
4                        1         Diploma
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       20 non-null     int64
 1   Name                     20 non-null     object
 2   Age                      19 non-null     float64
 3   Salary                   19 non-null     float64
 4   Department               20 non-null     object
 5   Position                 20 non-null     object
 6   Work Experience (Years)  20 non-null     int64
 7   Education Level          20 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 1.4+ KB
None
ID                         0
Name                       0
Age                        1
Salary                     1
Department                 0
Position                   0
Work Experience (Years)    0
Education Level            0
dtype: int64

### **Data Selection and Filtering**
* Extract only the Name and Salary columns.
* Filter employees who earn more than $50,000

In [185]:
#extract name and salary columns
df_extracted = df_new[['Name','Salary']]
#then shows name and salary of employees who make over 50,000
df_extracted.loc[df_extracted['Salary'] > 50000.0]

                 Name    Salary
2       Emma Williams   63419.0
3         David Brown   90636.0
5        James Garcia   94268.0
6     Sophia Martinez   58141.0
7   Benjamin Anderson  111910.0
8    Charlotte Thomas   96044.0
9       Daniel Wilson  107214.0
10      Amelia Taylor   73827.0
11      Matthew Moore   95820.0
12       Isabella Lee  102623.0
13       Ethan Harris  115450.0
14          Mia Clark   62299.0
15    Alexander Lewis   83585.0
16      Harper Walker  104044.0
17       William Hall   82557.0
18       Evelyn Young   89080.0

### **Data Aggregation**
* Find the average salary of employees.
* Count the number of employees in each department.

In [187]:
#average salary of employees
average_salary = df_new['Salary'].mean()
print(average_salary)
# group by department and count the number of employees in each
department_grouped=df_new.groupby('Department').count()
print(department_grouped)

82143.47368421052
            ID  Name  Age  Salary  Position  Work Experience (Years)  \
Department
Finance      3     3    3       3         3                        3
HR           5     5    4       5         5                        5
IT           2     2    2       2         2                        2
Marketing    2     2    2       1         2                        2
Operations   4     4    4       4         4                        4
Sales        4     4    4       4         4                        4

            Education Level
Department
Finance                   3
HR                        5
IT                        2
Marketing                 2
Operations                4
Sales                     4

### **Data Cleaning**
* Replace any missing Salary values with the mean salary.
* Drop rows where Age is missing.

In [189]:

# Replace missing salary with average salary 
df_new['Salary']=df_new['Salary'].fillna(df_new['Salary'].mean()) 
# drop missing age
df_cleaned = df_new.dropna(subset=['Age'])
df_cleaned

,ID,Name,Age,Salary,Department,Position,Work Experience (Years),Education Level
0,1,Alice Johnson,49.0,46910.000000,Operations,Consultant,13,PhD
1,2,Michael Smith,28.0,40206.000000,IT,Manager,9,Associate
2,3,Emma Williams,30.0,63419.000000,Sales,Analyst,15,PhD
3,4,David Brown,29.0,90636.000000,HR,Executive,13,Bachelor's
4,5,Olivia Jones,33.0,82143.473684,Marketing,Consultant,1,Diploma
5,6,James Garcia,55.0,94268.000000,Finance,Coordinator,7,Diploma
6,7,Sophia Martinez,54.0,58141.000000,Operations,Manager,9,Master's
7,8,Benjamin Anderson,44.0,111910.000000,Marketing,Manager,24,Bachelor's
8,9,Charlotte Thomas,45.0,96044.000000,Sales,Executive,1,Bachelor's
10,11,Amelia Taylor,56.0,73827.000000,Operations,Consultant,8,Diploma
11,12,Matthew Moore,43.0,95820.000000,Finance,Coordinator,24,PhD
12,13,Isabella Lee,48.0,102623.000000,IT,Manager,11,Bachelor's
13,14,Ethan Harris,56.0,115450.000000,HR,Manager,19,Associate
14,15,Mia Clark,22.0,62299.000000,HR,Consultant,17,Bachelor's
15,16,Alexander Lewis,56.0,83585.000000,Operations,Developer,8,Associate
16,17,Harper Walker,58.0,104044.000000,Finance,Consultant,3,Associate
17,18,William Hall,35.0,82557.000000,Sales,Manager,3,Bachelor's
18,19,Evelyn Young,24.0,89080.000000,Sales,Consultant,1,PhD
19,20,Henry Allen,22.0,42693.000000,HR,Manager,5,Master's

In [190]:
#check for missing values again
df_cleaned.isnull().sum()

ID                         0
Name                       0
Age                        0
Salary                     0
Department                 0
Position                   0
Work Experience (Years)    0
Education Level            0
dtype: int64

## **Task 3: Combined NumPy and Pandas Operations**

### **Converting a Column to a NumPy Array**
* Extract the Salary column as a NumPy array.
* Compute the standard deviation using NumPy.

In [193]:
#extract salary column as array
salary_array = df_cleaned['Salary'].to_numpy()
print(salary_array)
#standard deviation of array
print('Standard Deviation:', np.std(salary_array))

[ 46910.          40206.          63419.          90636.
  82143.47368421  94268.          58141.         111910.
  96044.          73827.          95820.         102623.
 115450.          62299.          83585.         104044.
  82557.          89080.          42693.        ]
Standard Deviation: 22310.34519866553

### **New Column Creation**
* Create a new column Salary_Bonus where each employee gets a 10% increase in salary

In [195]:
#new column with bonus
df_cleaned['Salary_Bonus'] = df_cleaned['Salary']*1.10
print(df_cleaned)

    ID               Name   Age         Salary  Department     Position  \
0    1      Alice Johnson  49.0   46910.000000  Operations   Consultant
1    2      Michael Smith  28.0   40206.000000          IT      Manager
2    3      Emma Williams  30.0   63419.000000       Sales      Analyst
3    4        David Brown  29.0   90636.000000          HR    Executive
4    5       Olivia Jones  33.0   82143.473684   Marketing   Consultant
5    6       James Garcia  55.0   94268.000000     Finance  Coordinator
6    7    Sophia Martinez  54.0   58141.000000  Operations      Manager
7    8  Benjamin Anderson  44.0  111910.000000   Marketing      Manager
8    9   Charlotte Thomas  45.0   96044.000000       Sales    Executive
10  11      Amelia Taylor  56.0   73827.000000  Operations   Consultant
11  12      Matthew Moore  43.0   95820.000000     Finance  Coordinator
12  13       Isabella Lee  48.0  102623.000000          IT      Manager
13  14       Ethan Harris  56.0  115450.000000          HR      Manager
14  15          Mia Clark  22.0   62299.000000          HR   Consultant
15  16    Alexander Lewis  56.0   83585.000000  Operations    Developer
16  17      Harper Walker  58.0  104044.000000     Finance   Consultant
17  18       William Hall  35.0   82557.000000       Sales      Manager
18  19       Evelyn Young  24.0   89080.000000       Sales   Consultant
19  20        Henry Allen  22.0   42693.000000          HR      Manager

    Work Experience (Years) Education Level   Salary_Bonus
0                        13             PhD   51601.000000
1                         9       Associate   44226.600000
2                        15             PhD   69760.900000
3                        13      Bachelor's   99699.600000
4                         1         Diploma   90357.821053
5                         7         Diploma  103694.800000
6                         9        Master's   63955.100000
7                        24      Bachelor's  123101.000000
8                         1      Bachelor's  105648.400000
10                        8         Diploma   81209.700000
11                       24             PhD  105402.000000
12                       11      Bachelor's  112885.300000
13                       19       Associate  126995.000000
14                       17      Bachelor's   68528.900000
15                        8       Associate   91943.500000
16                        3       Associate  114448.400000
17                        3      Bachelor's   90812.700000
18                        1             PhD   97988.000000
19                        5        Master's   46962.300000

/var/folders/_x/tdh8tq8d13x56xn7yvh2m24r0000gn/T/ipykernel_54292/1501872916.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Salary_Bonus'] = df_cleaned['Salary']*1.10

### **Grouping, Summarization and Saving**
* Group data by Department and find the total salary expense per department.
* Save the cleaned csv as project1_part2_data_cleaned.csv

In [211]:
#group by departnment, then total salary expense per department
expense = df_cleaned.groupby('Department')['Salary'].sum()
print(expense)

Department
Finance       294132.000000
HR            311078.000000
IT            142829.000000
Marketing     194053.473684
Operations    262463.000000
Sales         331100.000000
Name: Salary, dtype: float64

In [213]:
#save cleaned data
df_cleaned.to_csv('project1_part2_data_cleaned.csv', index=False)